name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: |
        sudo apt update
        sudo apt install libasound2-dev libudev-dev
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
